name = "cms"
main = "src/index.js"  # Changed to point to new modular structure
compatibility_date = "2025-02-01"

[[r2_buckets]]
binding = "media"
bucket_name = "media"

[[d1_databases]]
binding = "DB"
database_name = "music-stats"
database_id = "c1f2a231-d2aa-474d-9181-210a9fb11e7e"